### ISSUE TITLE
[TESTS] Create unit tests for functions

### ISSUE THREAD

**Issue by abannachGrafana** [grafana/fake-metrics-generator#3]
## Acceptance criteria

```[tasklist]
### Tasks
- [ ] Unit tests have been written
- [ ] Unit tests run in the ci/cd pipeline
- [ ] Code coverage is reported
```
